/*Copyright (c) 2015-2016 vcs1.com All Rights Reserved.
 This software is the confidential and proprietary information of vcs1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcs1.com*/

package com.testdbproject1.testdb7872;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * Table2 generated by hbm2java
 */
@Entity
@Table(name="TABLE2"
    ,schema="testdb7872"
)
public class Table2  implements java.io.Serializable
 {


private Integer id;
private String testName;
private Integer testColumn3;

    public Table2() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="ID", nullable=false, length=1)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="test_name")
    public String getTestName() {
        return this.testName;
    }
    
    public void setTestName(String testName) {
        this.testName = testName;
    }

    

    @Column(name="TestCOLUMN_3", length=1)
    public Integer getTestColumn3() {
        return this.testColumn3;
    }
    
    public void setTestColumn3(Integer testColumn3) {
        this.testColumn3 = testColumn3;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Table2) )
		 return false;

		 Table2 that = ( Table2 ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

